# Generated by Django 4.0.6 on 2022-08-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='commerce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=100)),
                ('productprice', models.IntegerField()),
                ('productimage', models.ImageField(upload_to='pics')),
                ('productdesc', models.TextField()),
            ],
        ),
    ]
