# Generated by Django 4.0.6 on 2022-08-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commerce',
            name='offers',
            field=models.BooleanField(default=False),
        ),
    ]
