# Generated by Django 4.0.6 on 2022-08-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_commerce_offers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commerce',
            name='productimage',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
    ]
