# Generated by Django 4.0.6 on 2022-08-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_commerce_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commerce',
            name='offers',
        ),
        migrations.AddField(
            model_name='commerce',
            name='large',
            field=models.BooleanField(default=False, verbose_name='Large'),
        ),
        migrations.AddField(
            model_name='commerce',
            name='medium',
            field=models.BooleanField(default=False, verbose_name='Medium'),
        ),
        migrations.AddField(
            model_name='commerce',
            name='small',
            field=models.BooleanField(default=False, verbose_name='Small'),
        ),
    ]
