# Generated by Django 4.0.6 on 2022-08-11 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_commerce_large_alter_commerce_medium_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commerce',
            old_name='small',
            new_name='l',
        ),
        migrations.RemoveField(
            model_name='commerce',
            name='large',
        ),
        migrations.RemoveField(
            model_name='commerce',
            name='medium',
        ),
    ]
