# Generated by Django 4.0.6 on 2022-08-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_small_commerce_l_remove_commerce_large_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commerce',
            old_name='l',
            new_name='small',
        ),
        migrations.AddField(
            model_name='commerce',
            name='large',
            field=models.BooleanField(default=False, verbose_name='large'),
        ),
        migrations.AddField(
            model_name='commerce',
            name='medium',
            field=models.BooleanField(default=False, verbose_name='medium'),
        ),
    ]
